# 거래량 상위 TOP 10

In [18]:
import pandas as pd
import requests
URL = f"https://finance.naver.com/sise/sise_quant.naver"
r = requests.get(URL)
top_vol = pd.read_html(r.text,  encoding = 'utf-8')[1]

In [19]:
top_vol.head(10)

,N,종목명,현재가,전일비,등락률,거래량,거래대금,매수호가,매도호가,시가총액,PER,ROE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,KODEX 200선물인버스2X,3105.0,40.0,+1.31%,173743016.0,536298.0,3100.0,3105.0,20332.0,NaN,NaN
2,2.0,KODEX 코스닥150선물인버스,4995.0,65.0,+1.32%,32800084.0,161626.0,4990.0,4995.0,3896.0,NaN,NaN
3,3.0,현대로템,24400.0,4200.0,+20.79%,30589460.0,717099.0,24400.0,24450.0,26631.0,36.36,5.01
4,4.0,KODEX 레버리지,15180.0,190.0,-1.24%,27750421.0,423802.0,15175.0,15180.0,23817.0,NaN,NaN
5,5.0,KODEX 인버스,4860.0,35.0,+0.73%,27318133.0,132249.0,4855.0,4860.0,8811.0,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,6.0,삼성 인버스 2X WTI원유 선물 ETN,120.0,5.0,+4.35%,23608452.0,2854.0,120.0,125.0,1796.0,NaN,NaN

In [20]:
# 거래량 순위 데이터 프레임에서 종목명이 nan 값인 행 삭제
na_index = top_vol[top_vol['종목명'].isna()].index
top_vol.drop(na_index,axis=0, inplace=True)
# 칼럼명 N 을 순위로 바꾸기
top_vol.rename(columns = {'N' : '순위'}, inplace = True)

In [21]:
top_vol

,순위,종목명,현재가,전일비,등락률,거래량,거래대금,매수호가,매도호가,시가총액,PER,ROE
1,1.0,KODEX 200선물인버스2X,3105.0,40.0,+1.31%,173743016.0,536298.0,3100.0,3105.0,20332.0,NaN,NaN
2,2.0,KODEX 코스닥150선물인버스,4995.0,65.0,+1.32%,32800084.0,161626.0,4990.0,4995.0,3896.0,NaN,NaN
3,3.0,현대로템,24400.0,4200.0,+20.79%,30589460.0,717099.0,24400.0,24450.0,26631.0,36.36,5.01
4,4.0,KODEX 레버리지,15180.0,190.0,-1.24%,27750421.0,423802.0,15175.0,15180.0,23817.0,NaN,NaN
5,5.0,KODEX 인버스,4860.0,35.0,+0.73%,27318133.0,132249.0,4855.0,4860.0,8811.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
153,96.0,고려산업,5500.0,200.0,-3.51%,1131623.0,6240.0,5490.0,5500.0,1372.0,26.70,4.32
154,97.0,혜인,7790.0,130.0,+1.70%,1088142.0,8495.0,7780.0,7790.0,990.0,18.07,4.98
155,98.0,범양건영,4515.0,80.0,+1.80%,1080914.0,4949.0,4510.0,4515.0,1121.0,56.44,5.79
156,99.0,한신기계,8600.0,180.0,-2.05%,1070602.0,9355.0,8600.0,8610.0,2790.0,83.50,4.86
157,100.0,KODEX 단기채권PLUS,103735.0,5.0,0.00%,1042656.0,108165.0,103735.0,103740.0,16347.0,NaN,NaN

In [22]:
# 거래 상위량 TOP 10
top_10_vol = top_vol[:10]
top_10_vol

,순위,종목명,현재가,전일비,등락률,거래량,거래대금,매수호가,매도호가,시가총액,PER,ROE
1,1.0,KODEX 200선물인버스2X,3105.0,40.0,+1.31%,173743016.0,536298.0,3100.0,3105.0,20332.0,NaN,NaN
2,2.0,KODEX 코스닥150선물인버스,4995.0,65.0,+1.32%,32800084.0,161626.0,4990.0,4995.0,3896.0,NaN,NaN
3,3.0,현대로템,24400.0,4200.0,+20.79%,30589460.0,717099.0,24400.0,24450.0,26631.0,36.36,5.01
4,4.0,KODEX 레버리지,15180.0,190.0,-1.24%,27750421.0,423802.0,15175.0,15180.0,23817.0,NaN,NaN
5,5.0,KODEX 인버스,4860.0,35.0,+0.73%,27318133.0,132249.0,4855.0,4860.0,8811.0,NaN,NaN
9,6.0,삼성 인버스 2X WTI원유 선물 ETN,120.0,5.0,+4.35%,23608452.0,2854.0,120.0,125.0,1796.0,NaN,NaN
10,7.0,대원화성,3275.0,365.0,+12.54%,22353589.0,78515.0,3270.0,3275.0,1351.0,-17.61,-9.53
11,8.0,신한 인버스 2X WTI원유 선물 ETN(H),110.0,5.0,+4.76%,17759819.0,1953.0,105.0,110.0,696.0,NaN,NaN
12,9.0,신한 인버스 2X 천연가스 선물 ETN,220.0,5.0,-2.22%,17563509.0,3876.0,215.0,220.0,428.0,NaN,NaN
13,10.0,평화산업,1805.0,415.0,+29.86%,15904381.0,27573.0,1805.0,0.0,991.0,-257.86,0.80

In [23]:
# 인덱스 지우고 데이터 프레임을 사진으로 저장하기

top_10_vol.set_index(keys='순위', drop=True, inplace=True)
dfi.export(top_10_vol, 'top_10_vol.png', max_cols=-1, max_rows=-1)

In [24]:
! pip install dataframe-image

Requirement already satisfied: dataframe-image in c:\anaconda3\lib\site-packages (0.1.1)
Requirement already satisfied: aiohttp in c:\anaconda3\lib\site-packages (from dataframe-image) (3.8.1)
Requirement already satisfied: requests in c:\anaconda3\lib\site-packages (from dataframe-image) (2.26.0)
Requirement already satisfied: nbconvert>=5 in c:\anaconda3\lib\site-packages (from dataframe-image) (6.1.0)
Requirement already satisfied: matplotlib>=3.1 in c:\anaconda3\lib\site-packages (from dataframe-image) (3.4.3)
Requirement already satisfied: pandas>=0.24 in c:\anaconda3\lib\site-packages (from dataframe-image) (1.3.4)
Requirement already satisfied: beautifulsoup4 in c:\anaconda3\lib\site-packages (from dataframe-image) (4.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\anaconda3\lib\site-packages (from matplotlib>=3.1->dataframe-image) (8.4.0)
Requirement already satisfied: numpy>=1.16 in c:\anaconda3\lib\site-packages (from matplotlib>=3.1->dataframe-image) (1.20.3)
Requirement already satisfied: pyparsing>=2.2.1 in c:\anaconda3\lib\site-packages (from matplotlib>=3.1->dataframe-image) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\anaconda3\lib\site-packages (from matplotlib>=3.1->dataframe-image) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\anaconda3\lib\site-packages (from matplotlib>=3.1->dataframe-image) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\anaconda3\lib\site-packages (from matplotlib>=3.1->dataframe-image) (0.10.0)
Requirement already satisfied: six in c:\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.1->dataframe-image) (1.16.0)
Requirement already satisfied: entrypoints>=0.2.2 in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (0.3)
Requirement already satisfied: traitlets>=5.0 in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (5.1.0)
Requirement already satisfied: defusedxml in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (0.7.1)
Requirement already satisfied: jinja2>=2.4 in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (2.11.3)
Requirement already satisfied: bleach in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (4.0.0)
Requirement already satisfied: jupyterlab-pygments in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (0.1.2)
Requirement already satisfied: nbformat>=4.4 in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (5.1.3)
Requirement already satisfied: testpath in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (0.5.0)
Requirement already satisfied: pygments>=2.4.1 in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (2.10.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (1.4.3)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (0.5.3)
Requirement already satisfied: jupyter-core in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (4.8.1)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\anaconda3\lib\site-packages (from nbconvert>=5->dataframe-image) (0.8.4)
Requirement already satisfied: MarkupSafe>=0.23 in c:\anaconda3\lib\site-packages (from jinja2>=2.4->nbconvert>=5->dataframe-image) (1.1.1)
Requirement already satisfied: nest-asyncio in c:\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe-image) (1.5.1)
Requirement already satisfied: async-generator in c:\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe-image) (1.10)
Requirement already satisfied: jupyter-client>=6.1.5 in c:\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe-image) (6.1.12)
Requirement already satisfied: tornado>=4.1 in c:\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe-image) (6.1)
Requirement already satisfied: pyzmq>=13 in c:\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert>=5->dataframe-image) (19.0.2)
Requirement already satisfied: pywin32>=1.0 in c:\anaconda3\lib\site-packages (from jupyter-core->nbconvert>=5->dataframe-image) (228)
Requirement already satisfied: ipython-genutils in c:\anaconda3\lib\site-packages (from nbformat>=4.4->nbconvert>=5->dataframe-image) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\anaconda3\lib\site-packages (from nbformat>=4.4->nbconvert>=5->dataframe-image) (3.2.0)
Requirement already satisfied: setuptools in c:\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=5->dataframe-image) (58.0.4)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=5->dataframe-image) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=5->dataframe-image) (21.2.0)
Requirement already satisfied: pytz>=2017.3 in c:\anaconda3\lib\site-packages (from pandas>=0.24->dataframe-image) (2021.3)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\anaconda3\lib\site-packages (from aiohttp->dataframe-image) (6.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\anaconda3\lib\site-packages (from aiohttp->dataframe-image) (1.7.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\anaconda3\lib\site-packages (from aiohttp->dataframe-image) (1.3.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\anaconda3\lib\site-packages (from aiohttp->dataframe-image) (4.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\anaconda3\lib\site-packages (from aiohttp->dataframe-image) (2.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\anaconda3\lib\site-packages (from aiohttp->dataframe-image) (1.2.0)
Requirement already satisfied: idna>=2.0 in c:\anaconda3\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->dataframe-image) (3.2)
Requirement already satisfied: soupsieve>1.2 in c:\anaconda3\lib\site-packages (from beautifulsoup4->dataframe-image) (2.2.1)
Requirement already satisfied: packaging in c:\anaconda3\lib\site-packages (from bleach->nbconvert>=5->dataframe-image) (21.0)
Requirement already satisfied: webencodings in c:\anaconda3\lib\site-packages (from bleach->nbconvert>=5->dataframe-image) (0.5.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests->dataframe-image) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests->dataframe-image) (1.26.7)

In [25]:
import dataframe_image as dfi

# 데이터 프레임을 이미지로 저장
dfi.export(top_10_vol, 'top_10_vol.png', max_cols=-1, max_rows=-1)

# 상승 TOP 10

In [26]:
import pandas as pd
import requests
URL = f"https://finance.naver.com/sise/sise_rise.naver"
r = requests.get(URL)
top_rise = pd.read_html(r.text,  encoding = 'utf-8')[1]

In [27]:
na_index = top_rise[top_rise['종목명'].isna()].index
top_rise.drop(na_index,axis=0, inplace=True)

In [28]:
# 상승 종목 순위 데이터프레임
top_rise.head()

,N,종목명,현재가,전일비,등락률,거래량,매수호가,매도호가,매수총잔량,매도총잔량,PER,ROE
1,1.0,현대로템,24400.0,4200.0,+20.79%,30589460.0,24400.0,24450.0,352350.0,488658.0,36.36,5.01
2,2.0,사조씨푸드,5950.0,860.0,+16.90%,9020790.0,5950.0,5960.0,19877.0,59276.0,10.14,4.47
3,3.0,대원화성,3275.0,365.0,+12.54%,22353589.0,3270.0,3275.0,76552.0,30589.0,-17.61,-9.53
4,4.0,SNT중공업,7820.0,790.0,+11.24%,4563838.0,7820.0,7830.0,19616.0,4520.0,27.06,9.44
5,5.0,한화에어로스페이스,49900.0,4250.0,+9.31%,1301122.0,49850.0,49900.0,5507.0,51054.0,12.51,9.21

In [29]:
# 거래 상위량 TOP 10
top_10_rise = top_rise[:10]
top_10_rise

,N,종목명,현재가,전일비,등락률,거래량,매수호가,매도호가,매수총잔량,매도총잔량,PER,ROE
1,1.0,현대로템,24400.0,4200.0,+20.79%,30589460.0,24400.0,24450.0,352350.0,488658.0,36.36,5.01
2,2.0,사조씨푸드,5950.0,860.0,+16.90%,9020790.0,5950.0,5960.0,19877.0,59276.0,10.14,4.47
3,3.0,대원화성,3275.0,365.0,+12.54%,22353589.0,3270.0,3275.0,76552.0,30589.0,-17.61,-9.53
4,4.0,SNT중공업,7820.0,790.0,+11.24%,4563838.0,7820.0,7830.0,19616.0,4520.0,27.06,9.44
5,5.0,한화에어로스페이스,49900.0,4250.0,+9.31%,1301122.0,49850.0,49900.0,5507.0,51054.0,12.51,9.21
9,6.0,TCC스틸,13800.0,900.0,+6.98%,2118210.0,13750.0,13800.0,68031.0,215624.0,10.06,21.49
10,7.0,메리츠 인버스 2X 대표 농산물 선물 ETN(H),15480.0,1005.0,+6.94%,52155.0,15455.0,15480.0,31753.0,48707.0,NaN,NaN
11,8.0,미래에셋 인버스 2X 옥수수 선물 ETN,17810.0,1145.0,+6.87%,10523.0,17810.0,17855.0,60024.0,59985.0,NaN,NaN
12,9.0,한성기업,6560.0,420.0,+6.84%,2522620.0,6560.0,6580.0,17500.0,5046.0,-4.82,-15.80
13,10.0,하나 인버스 2X 옥수수 선물 ETN(H),15965.0,1000.0,+6.68%,7840.0,15935.0,15965.0,25130.0,40008.0,NaN,NaN

In [30]:
# 인덱스 지우고 데이터 프레임을 사진으로 저장하기

top_10_rise.set_index(keys='순위', drop=True, inplace=True)
dfi.export(top_10_rise, 'top_10_rise.png', max_cols=-1, max_rows=-1)

KeyError: "None of ['순위'] are in the columns"

# 시가 총액 TOP 10

In [ ]:
import pandas as pd
URL = f"https://finance.naver.com/sise/sise_market_sum.naver"
r = requests.get(URL)
top_sum = pd.read_html(r.text,  encoding = 'utf-8')[1]
na_index = top_sum[top_sum['종목명'].isna()].index
top_sum.drop(na_index,axis=0, inplace=True)
top_sum.head()

In [ ]:
# 시가 총액 TOP 10
top_10_sum = top_sum[:10]
top_10_sum

In [ ]:
# 인덱스 지우고 데이터 프레임을 사진으로 저장하기

top_10_sum.set_index(keys='순위', drop=True, inplace=True)
dfi.export(top_10_sum, 'top_10_sum.png', max_cols=-1, max_rows=-1)

# 하락 TOP 10

In [ ]:
import pandas as pd
import requests
URL = f"https://finance.naver.com/sise/sise_fall.naver"
r = requests.get(URL)
top_fall = pd.read_html(r.text,  encoding = 'utf-8')[1]
na_fall = top_fall[top_fall['종목명'].isna()].index
top_fall.drop(na_index,axis=0, inplace=True)
top_fall.head()

In [ ]:
# 하락 TOP 10
top_10_fall = top_fall[:10]
top_10_fall

In [ ]:
# 인덱스 지우고 데이터 프레임을 사진으로 저장하기

top_10_fall.set_index(keys='순위', drop=True, inplace=True)
dfi.export(top_10_fall, 'top_10_sum.png', max_cols=-1, max_rows=-1)

In [25]:
# 거래량 : quant
# 상승 : rise
# 하락 : fall
# 시가총액 : market_sum

type = input('키워드를 입력해주세요: ')
URL = f"https://finance.naver.com/sise/sise_{type}.naver"
URL

키워드를 입력해주세요: rise

'https://finance.naver.com/sise/sise_rise.naver'

In [26]:
r = requests.get(URL)
top_all = pd.read_html(r.text,  encoding = 'utf-8')[1]
# 거래량 순위 데이터 프레임에서 종목명이 nan 값인 행 삭제
na_index = top_all[top_all['종목명'].isna()].index
top_all.drop(na_index,axis=0, inplace=True)

# Top10
top_10 = top_all[:10]
top_10

,N,종목명,현재가,전일비,등락률,거래량,매수호가,매도호가,매수총잔량,매도총잔량,PER,ROE
1,1.0,현대로템,24400.0,4200.0,+20.79%,30589460.0,24400.0,24450.0,352350.0,488658.0,36.36,5.01
2,2.0,사조씨푸드,5950.0,860.0,+16.90%,9020790.0,5950.0,5960.0,19877.0,59276.0,10.14,4.47
3,3.0,대원화성,3275.0,365.0,+12.54%,22353589.0,3270.0,3275.0,76552.0,30589.0,-17.61,-9.53
4,4.0,SNT중공업,7820.0,790.0,+11.24%,4563838.0,7820.0,7830.0,19616.0,4520.0,27.06,9.44
5,5.0,한화에어로스페이스,49900.0,4250.0,+9.31%,1301122.0,49850.0,49900.0,5507.0,51054.0,12.51,9.21
9,6.0,TCC스틸,13800.0,900.0,+6.98%,2118210.0,13750.0,13800.0,68031.0,215624.0,10.06,21.49
10,7.0,메리츠 인버스 2X 대표 농산물 선물 ETN(H),15480.0,1005.0,+6.94%,52155.0,15455.0,15480.0,31753.0,48707.0,NaN,NaN
11,8.0,미래에셋 인버스 2X 옥수수 선물 ETN,17810.0,1145.0,+6.87%,10523.0,17810.0,17855.0,60024.0,59985.0,NaN,NaN
12,9.0,한성기업,6560.0,420.0,+6.84%,2522620.0,6560.0,6580.0,17500.0,5046.0,-4.82,-15.80
13,10.0,하나 인버스 2X 옥수수 선물 ETN(H),15965.0,1000.0,+6.68%,7840.0,15935.0,15965.0,25130.0,40008.0,NaN,NaN